export default [
    { KEY: 'ko', NAME: '한국어' },
    { KEY: 'ja', NAME: '일본어' },
    { KEY: 'zh-CN', NAME: '중국어 간체' },
    { KEY: 'zh-TW', NAME: '중국어 번체' },
    { KEY: 'hi', NAME: '힌디어' },
    { KEY: 'en', NAME: '영어' },
    { KEY: 'es', NAME: '스페인어' },
    { KEY: 'fr', NAME: '프랑스어' },
    { KEY: 'de', NAME: '독일어' },
    { KEY: 'pt', NAME: '포르투갈어' },
    { KEY: 'vi', NAME: '베트남어' },
    { KEY: 'id', NAME: '인도네시아어' },
    { KEY: 'fa', NAME: '페르시아어' },
    { KEY: 'ar', NAME: '아랍어' },
    { KEY: 'mm', NAME: '미얀마어' },
    { KEY: 'th', NAME: '태국어' },
    { KEY: 'ru', NAME: '러시아어' },
    { KEY: 'it', NAME: '이탈리아어' },
] as const;
